---

#- name: Debug hosts vars
#  debug: 
#    var: hostvars

- name: Create Filebeat group
  group:
    name: filebeat
    state: present

- name: Add users to Filebeat group
  user:
    name: "{{ item }}"
    groups: filebeat
    append: true
  with_items: "{{ users }}"

- name: Create Filebeat system user
  user:
    name: "filebeat"
    system: yes
    createhome: no
    groups: filebeat

- name: Copy filebeat reporsitory file
  copy:
    src: "filebeat.repo"
    dest: "/etc/yum.repos.d/filebeat.repo"
    mode: 0755

- name: Create filebeat home directory
  file:
    path: "{{ filebeat_home }}"
    mode: 0777
    owner: "filebeat"
    group: "filebeat"
    state: directory

- name: Copy filebeat configuration file
  template:
    src: "filebeat.yml.j2"
    dest: "{{ filebeat_home }}/filebeat.yml"
    mode: 0744

